### ISSUE TITLE
Youtube API is exposed.

### ISSUE THREAD

**Issue by anmol5varma** [bennymeier/youtube-downloader#50]
Hey mate, great project btw. Kudos to that. Although I did notice that your youtube API key is public. You delete this key in your google console. Create a new one and inject it when you are deploying your code using env variables. Just a suggestion.

**Comment by bennymeier** [comment]
Hey dude, thanks for your message. I know that my YT API key is public and also my MongoDB Atlas Key, but with the next update I will change it to env. variables, thank you for your message!

**Comment by bennymeier** [comment]
File ```nodemon.json``` added locally with env. variables. Removed old API keys and change it to new ones.
